# Generated by Django 3.1.2 on 2021-02-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название команды')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Счет')),
                ('link', models.CharField(blank=True, default='', max_length=100, verbose_name='Социальные ссылки')),
                ('url', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Ссылка для вступления в команду')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TeamsLeaders',
            fields=[
                ('team_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.teams', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Лидер',
                'verbose_name_plural': 'Лидеры',
            },
        ),
    ]
