# Generated by Django 3.1.2 on 2020-11-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Счет')),
                ('link', models.TextField(null=True, verbose_name='Социальные ссылки')),
                ('url', models.CharField(max_length=250, verbose_name='Ссылка для вступления в команду')),
            ],
        ),
    ]
