# Generated by Django 3.1.2 on 2021-03-31 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210331_2234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210331_2234'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
        migrations.AddField(
            model_name='teams',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='teamsleaders',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userAuth.user', verbose_name='Лидер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teams',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Социальные ссылки'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Ссылка для вступления в команду'),
        ),
        migrations.AlterUniqueTogether(
            name='teamsleaders',
            unique_together={('user_id', 'team_id')},
        ),
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=None, null=True, verbose_name='Баллы')),
                ('is_came', models.BooleanField(blank=True, default=None, null=True, verbose_name='Команда пришла')),
                ('checkpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.checkpoint', verbose_name='Чекпоинт')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teams', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Результат чекпоинта',
                'verbose_name_plural': 'Результаты чекпоинтов',
                'unique_together': {('checkpoint_id', 'team_id')},
            },
        ),
    ]
