# Generated by Django 3.1.2 on 2021-03-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210313_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Баллы'),
        ),
    ]
