# Generated by Django 3.1.2 on 2020-11-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20201126_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamsleaders',
            options={'verbose_name': 'Лидер', 'verbose_name_plural': 'Лидеры'},
        ),
    ]
