# Generated by Django 3.1.2 on 2021-02-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210219_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
