# Generated by Django 3.1.2 on 2020-12-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20201204_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsleaders',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.teams'),
        ),
    ]
