# Generated by Django 3.1.2 on 2020-11-04 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_teams_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.CreateModel(
            name='Teams_leaders',
            fields=[
                ('team_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='team.teams')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'team_id')},
            },
        ),
    ]
