# Generated by Django 3.1.2 on 2021-03-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210324_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checked',
            options={'verbose_name': 'Результат чекпоинта', 'verbose_name_plural': 'Результаты чекпоинтов'},
        ),
    ]
