# Generated by Django 3.1.2 on 2021-01-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20201204_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True, unique=True, verbose_name='Ссылка для вступления в команду'),
        ),
    ]
