# Generated by Django 3.1.2 on 2020-11-04 21:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20201105_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams_leaders',
            new_name='TeamsLeaders',
        ),
    ]
