# Generated by Django 3.1.2 on 2020-11-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20201105_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='leader',
        ),
    ]
