# Generated by Django 3.1.2 on 2021-03-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210307_0137'),
        ('main', '0003_checkpoint_news_rating'),
        ('team', '0004_auto_20210219_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
        migrations.AddField(
            model_name='teams',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Задание'),
        ),
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.checkpoint', verbose_name='Чекпоинт')),
                ('score', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Баллы')),
                ('is_came', models.NullBooleanField(default=None, verbose_name='Команда пришла')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teams', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Чекпоинт',
                'verbose_name_plural': 'Чекпоинты',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
