# Generated by Django 3.1.2 on 2021-03-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_checkpoint_news_rating'),
        ('team', '0005_auto_20210307_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checked',
            options={'verbose_name': 'Чекпоинт', 'verbose_name_plural': 'Чекпоинты'},
        ),
        migrations.RenameField(
            model_name='checked',
            old_name='team',
            new_name='team_id',
        ),
        migrations.AddField(
            model_name='checked',
            name='checkpoint_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.checkpoint', verbose_name='Чекпоинт'),
        ),
        migrations.AddField(
            model_name='checked',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='checked',
            unique_together={('checkpoint_id', 'team_id')},
        ),
        migrations.AlterModelTable(
            name='checked',
            table=None,
        ),
        migrations.RemoveField(
            model_name='checked',
            name='checkpoint',
        ),
    ]
