# Generated by Django 3.1.2 on 2021-01-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210112_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='description',
        ),
    ]
