# Generated by Django 3.1.2 on 2020-11-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_remove_teams_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='link',
            field=models.CharField(max_length=2048, null=True, verbose_name='Социальные ссылки'),
        ),
    ]
