# Generated by Django 3.1.2 on 2020-11-04 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20201105_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsleaders',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamsleaders',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='team.teams'),
        ),
    ]
