# Generated by Django 3.1.2 on 2021-03-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20210307_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='is_came',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Команда пришла'),
        ),
    ]
