# Generated by Django 3.1.2 on 2021-03-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20210307_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checked',
            old_name='checkpoint_id',
            new_name='checkpoint',
        ),
        migrations.RenameField(
            model_name='checked',
            old_name='team_id',
            new_name='team',
        ),
    ]
