# Generated by Django 3.1.2 on 2020-11-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20201105_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='link',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Социальные ссылки'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка для вступления в команду'),
        ),
    ]
