# Generated by Django 3.1.2 on 2020-11-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20201105_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название команды'),
        ),
    ]
