# Generated by Django 3.1.2 on 2020-11-26 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0010_auto_20201108_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsleaders',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='team.teams'),
        ),
        migrations.AlterField(
            model_name='teamsleaders',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
