# Generated by Django 3.1.2 on 2021-03-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_checkpoint'),
        ('team', '0010_auto_20210308_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='checkpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.checkpoint', verbose_name='Чекпоинт'),
        ),
    ]
