# Generated by Django 3.1.2 on 2021-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20210201_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Социальные ссылки'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='url',
            field=models.CharField(blank=True, default='', unique=True, max_length=100, verbose_name='Ссылка для вступления в команду'),
        ),
    ]
