# Generated by Django 3.1.2 on 2021-02-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20210201_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
    ]
