# Generated by Django 3.1.2 on 2021-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_remove_teams_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teams',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Счет'),
        ),
    ]
