# Generated by Django 3.1.2 on 2021-02-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20210218_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
    ]
