# Generated by Django 3.1.2 on 2021-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_auto_20210219_0029'),
    ]

    operations = [

    ]
