# Generated by Django 3.1.2 on 2021-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_auto_20210219_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='teams',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название команды'),
        ),
    ]
