# Generated by Django 3.1.2 on 2021-02-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_auto_20210219_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
    ]
