# Generated by Django 3.1.2 on 2021-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество участников в команде'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество команд'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
