# Generated by Django 3.1.2 on 2021-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('start_date', models.DateTimeField(unique=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(unique=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Чекпоинт',
                'verbose_name_plural': 'Чекпоинты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='news_image', verbose_name='Изображение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('max', models.PositiveIntegerField(verbose_name='Максимальный балл')),
                ('cof', models.FloatField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество участников в команде'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество команд'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
