# Generated by Django 3.1.2 on 2021-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210313_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Имя'),
        ),
    ]
