# Generated by Django 3.1.2 on 2021-03-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20210308_2033'),
        ('main', '0003_checkpoint_news_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkpoint',
        ),
    ]
