# Generated by Django 3.1.2 on 2021-03-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_checkpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Заголовок')),
                ('start_date', models.DateTimeField(unique=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(unique=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Чекпоинт',
                'verbose_name_plural': 'Чекпоинты',
            },
        ),
    ]
