# Generated by Django 3.1.2 on 2021-03-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заголовок'),
        ),
    ]
