# Generated by Django 3.1.2 on 2021-01-12 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0005_auto_20210112_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('task', models.TextField(verbose_name='Задание')),
                ('task_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл задания')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Максимальный балл за задание')),
                ('deadline', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дедлайн')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(verbose_name='Решение')),
                ('solution_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл решения')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Баллы за задание')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Задача')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teams', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
    ]
