# Generated by Django 3.1.2 on 2021-02-18 21:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('task', models.CharField(max_length=100, verbose_name='Задание')),
                ('task_file', models.FileField(blank=True, null=True, upload_to='tasks/', verbose_name='Файл задания')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Максимальный балл за задание')),
                ('deadline', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дедлайн')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_file', models.FileField(upload_to='solution/', verbose_name='Файл решения')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Баллы за задание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
    ]
