# Generated by Django 3.1.2 on 2021-04-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='score',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на решение'),
        ),
        migrations.AddField(
            model_name='solution',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_file',
            field=models.FileField(blank=True, default='', upload_to='solution/', verbose_name='Файл решения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Задание'),
        ),
    ]
