# Generated by Django 3.1.2 on 2021-03-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20210219_0131'),
        ('tasks', '0002_auto_20210219_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='solution',
            name='solution_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на решение'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='solution/', verbose_name='Файл решения'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Задание'),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='score',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='task',
        ),
    ]
