# Generated by Django 3.1.2 on 2021-01-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solution',
        ),
    ]
