# Generated by Django 3.1.2 on 2021-03-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_file',
            field=models.FileField(blank=True, default='', upload_to='solution/', verbose_name='Файл решения'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на решение'),
        ),
    ]
