# Generated by Django 3.1.2 on 2021-01-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210127_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_file',
            field=models.FileField(null=True, upload_to='solution/', verbose_name='Файл решения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/', verbose_name='Файл задания'),
        ),
    ]
