# Generated by Django 3.1.2 on 2021-03-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20210310_2124'),
        ('tasks', '0006_solution_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkpoint',
        ),
    ]
