# Generated by Django 3.1.2 on 2021-01-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210128_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_file',
            field=models.FileField(default=0, upload_to='solution/', verbose_name='Файл решения'),
            preserve_default=False,
        ),
    ]
