# Generated by Django 3.1.2 on 2021-02-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_remove_teams_score'),
        ('tasks', '0007_auto_20210128_2123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('team', 'task')},
        ),
    ]
