# Generated by Django 3.1.2 on 2021-02-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRepresentatives',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userAuth.user', verbose_name='Представитель компании')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Представитель',
                'verbose_name_plural': 'Представители',
            },
        ),
    ]
