# Generated by Django 3.1.2 on 2021-03-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyrepresentatives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyrepresentatives',
            old_name='company_id',
            new_name='company',
        ),
    ]
