# Generated by Django 3.1.2 on 2020-10-12 16:58

from django.db import migrations
import userAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userAuth.models.Manager()),
            ],
        ),
    ]
