# Generated by Django 3.1.2 on 2020-11-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Лидер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_specialist',
            field=models.BooleanField(default=False, verbose_name='Специалист'),
        ),
    ]
