# Generated by Django 3.1.2 on 2020-11-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20201104_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_leader',
        ),
    ]
