# Generated by Django 3.1.2 on 2021-03-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20210220_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False, verbose_name='Ревизорро'),
        ),
    ]
