# Generated by Django 3.1.2 on 2021-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20210313_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False, verbose_name='Аудитор'),
        ),
    ]
