# Generated by Django 3.1.2 on 2020-11-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_remove_user_is_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
